apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: securitytestinglab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
